### PR TITLE
Fix up/down keys reversed in `resize-window-alias-list`

### PR DESCRIPTION
**Pull request by knu**

### CODE REVIEW

**Comment by dpsutton** [comment]
@knu thanks so much for the pull request. do you think you could update the tests at https://github.com/dpsutton/resize-window/blob/master/test/resize-window-test.el#L11 as well so that the checks pass? I appreciate you catching this and submitting a patch.

**Comment by dpsutton** [comment]
meh, it's simple enough. thanks a lot for the pull request. sorry i missed such an easy bug.

**Comment by knu** [comment]
Ah, right, thanks for merging this and updating the test!

**Comment by dpsutton** [comment]
no problem. i cut a release as well so there should be an update on melpa whenever their scripts run their updates for the day. thanks again @knu

**Pull request merged**
